version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      - backend
    ports:
      - 5433:5432

  graduate.work.server:
    image: bentivimon/education:latest
    build:
      context: ../Server/src
      dockerfile: ./GraduateWork.Server.Api/Dockerfile
    container_name: graduate.work.server
    ports:
      - 5000:80
    networks: 
      - backend
    environment:
      - ConnectionStrings:DefaultConnection=User ID=root;Password=root;Host=postgres;Database=GraduateWork;Pooling=true;
    depends_on:
      - postgres

networks:
  backend:
