version: '3.5'

networks:
  backend:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=x7AsdhA8732
      - POSTGRES_USER=root
    networks:
      - backend
    ports:
      - 5432:5432

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock       
      - ~/.docker/config.json:/config.json:ro
    command:
      --interval 300
      --cleanup
      --include-stopped
    networks:
      - backend
    
  chatBot-api:
    image: bentivimon/education:chatbot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ViberApiOptions:AccessKey=4ae59b509327df09-ed43699212aa009c-95c72ff01fef7b11
    networks:
      - backend
    ports:
      - 5000:80
